# SPDX-FileCopyrightText: Copyright (c) 2014-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  directory: repo
merge:
  script: |
    bundle lock --no-color
    bundle install --no-color
    LC_ALL=en_US.UTF-8 bundle exec rake
