#
# Just run "bundle"
#
source 'https://rubygems.org'
#ruby '2.2.2'

gem 'jekyll', '~>3.2'
gem 'jekyll-feed'
gem 'jekyll-bits'
gem 'jekyll-gist'
gem 'jekyll-paginate'
gem 'jekyll-plantuml'
gem 'jekyll-sass'
gem 'jekyll-sass-converter'
gem 'jekyll-sitemap'
gem 'jekyll-redirect-from'
gem 'jekyll-related-posts'

gem 'rake', '~>12.0'
gem 'sass', '~>3.4'
gem 'nokogiri', '~>1.7'
gem 'mail', '~>2.6'
gem 'uuidtools', '~>2.1'
gem 'redcarpet', '~>3.4'
gem 'nuggets', '~>1.5'
gem 'pygments.rb', '~>1.1'
gem 'rainbow', '~>2.2'
gem 'w3c_validators', '~>1.3'
gem 'trollop', '~>2.1'
gem 'scss_lint', '~>0.53'
gem 'html-proofer', '~>3.6'
gem 'rubocop', '~>0.48'
gem 'rubocop-rspec', '~>1.15'
gem 'jslint', '~>1.2'
gem 'fontcustom', '~>1.3'
gem 'fastimage', '~>2.1'
