#
# Just run "bundle"
#
source 'https://rubygems.org'

gem 'jekyll', '4.0.1'
gem 'jekyll-feed'
gem 'jekyll-bits'
gem 'jekyll-gist'
gem 'jekyll-paginate'
gem 'jekyll-plantuml'
gem 'jekyll-sass'
gem 'jekyll-sass-converter'
gem 'jekyll-sitemap'
gem 'jekyll-redirect-from'
# gem 'jekyll-related-posts'

gem 'fastimage', '2.1.5'
gem 'fontcustom', '2.0.0'
gem 'jslint', '1.2.0'
gem 'html-proofer', '3.7.5'
gem 'kramdown', '2.1'
gem 'liquid', '4.0.1'
gem 'mail', '2.7.1'
gem 'nokogiri', '1.9.1'
gem 'nuggets', '1.6.0'
gem 'pygments.rb', '1.2.1'
gem 'rainbow', '2.2.2'
gem 'rake', '12.3.2'
gem 'redcarpet', '3.4.0'
gem 'rubocop', '0.62.0'
gem 'rubocop-rspec', '1.30.1'
gem 'sass', '3.7.2'
gem 'scss_lint', '0.57.1'
gem 'trollop', '2.9.9'
gem 'uuidtools', '2.1.5'
gem 'w3c_validators', '1.3.4'
