# SPDX-FileCopyrightText: Copyright (c) 2014-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: copyrights
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  copyrights:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: yegor256/copyrights-action@0.0.12
        with:
          globs: >-
            **/LICENSE.txt
            **/*.sh
            **/*.rb
            **/*.scss
            **/*.js
            **/*.yml
            **/*.xml
            **/*.tex
            **/*.cls
          ignore: >-
            js/snowflakes.min.js
            _samples/**
